version: '3.3'

services:

  redis:
    container_name: redis
    ports:
      - 6379:6379
    image: redis:latest
    volumes:
      - ./rate-limit-redis:/data
    networks:
      - rate-limit-network
    
  rate-limit:
    container_name: rate_limit
    ports:
      - 8000:8000
    build: .
    networks:
      - rate-limit-network
    environment:
      - RHost=redis
      - RPort=6379
      - RDB=0
    restart: always
    depends_on:
      - redis
    command: >
      python app.py

networks:
  rate-limit-network:
    driver: bridge
volumes:
  rate-limit-redis:
    driver: local
